### PR TITLE
Hamzahsn/feat/update styles

### PR DESCRIPTION
**Pull request by hamzahsn**
This PR...

## Changes

- This PR is about adjusting the styles to match the updated design.

## Fixes

-

## How to test it

-

## screenshots

-

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Comment by olensmar** [comment]
comparing to the design at https://xd.adobe.com/view/eda29c5e-e9b2-4649-95e4-fefe4eeec48d-b8f1/ 
- "Ended at" column should be "Started At"
- "Name" and "Started At" columns look to be left-aligned - not sure if they are in yours
- The labels in the design look to me to be of a light-gray color - not pure white?
- Spacing between the Filter buttons is different

**Comment by hamzahsn** [comment]
> * Name" and "Started At" columns look to be left-a

- Sorry if I didn't understand you correctly, but I can see that it is "Started At" and not "Ended At", or not?
- I think I understood you, I will take a look on them.
- you mean Name, Started At...? then it is a good catch! 
- As far as I can see it is about 10px in the design, and I have set it in rems to be equal to that, so idk why it happened to take a little more, but I have set the unit to px.

**Review by olensmar — CHANGES_REQUESTED** [review]
see comment..

**Review by olensmar — CHANGES_REQUESTED** [review]
see comment!

**Review by nicufk — APPROVED** [review]

**Pull request merged**
